version: '2'
services:
  app:
    container_name: node-container-users-app
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo-container-users-db
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis-container-users-cache
    image: redis
    ports:
      - '6379:6379'
